routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
})->name('welcome');

Auth::routes();

Route::get('dashboard', 'HomeController@index')->name('home');

Route::resource('item_user', 'ItemUserController', ['except' => ['show']]);
Route::get('del_item_user', 'ItemUserController@del_item_user');
Route::get('item_user/{userId}', 'ItemUserController@show');
Route::get('users_progress', 'ItemUserController@progress');

Route::get('item/present/{itemId}', 'ItemController@present');
Route::get('item/present/{itemId}/{progress}', 'ItemUserController@store_progress');
Route::get('item/present/{itemId}/indexes/{indexes}', 'ItemUserController@store_indexes');

Route::get('item/create/activ/{itemId}', 'ItemController@activ');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('exams','ExamsContoller');

    Route::get('preguntas/{id}','QuestionController@index');
    Route::get('preguntas/create/{id}','QuestionController@create');
    Route::get('preguntas/edit/{exam_id}/{id}','QuestionController@edit');
    Route::post('preguntas/store/{id}','QuestionController@store');
    Route::put('preguntas/update/{exam_id}/{id}','QuestionController@update');
    Route::delete('preguntas/delete/{exam_id}/{id}','QuestionController@destroy');

    Route::resource('userExam','UserExamController');
    Route::resource('estadisticas','EstadisticasController');
    Route::get('exam/{exam_id}/{index}','UserExamController@examen');
    Route::post('next/{exam_id}/{index}','UserExamController@subir');
    Route::post('calificar/{examid}','UserExamController@calificar');
    Route::post('salvar/{examid}/{cali}','UserExamController@salvar_cali');

    Route::resource('/sendComentarios','ComentariosController');

    Route::resource('category', 'CategoryController', ['except' => ['show']]);
    Route::resource('tag', 'TagController', ['except' => ['show']]);
    Route::resource('item', 'ItemController', ['except' => ['show']]);
    Route::resource('path', 'PathController', ['except' => ['show']]);
    Route::resource('grades', 'GradesController', ['except' => ['show']]);
    Route::get('grades/{userid}', 'GradesController@grades');
    Route::resource('curso', 'CourseController', ['except' => ['show']]);
    Route::resource('role', 'RoleController', ['except' => ['show', 'destroy']]);
    Route::resource('user', 'UserController', ['except' => ['show']]);
    Route::resource('bitacora', 'BitacoraController', ['except' => ['show']]);
    Route::get('transcription/{itemId}', 'ItemController@transcription');
    Route::get('/transcription/slide/{itemId}', 'ItemController@slide');
    Route::post('/transcription/register/{itemId}', 'ItemController@create_slide_trans');
    Route::delete('/transcription/delete/{slideId}/{itemId}', 'ItemController@destroy_slide_transcription');
    Route::get('/transcription/edit/{itemId}/{slideId}', 'ItemController@update_show');
    Route::post('/transcription/update/{itemId}/{slideId}', 'ItemController@update_slide');
    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
    Route::get('{page}', ['as' => 'page.index', 'uses' => 'PageController@index']);


});

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'color'];

    /**
     * Get the items of the tag
     *
     * @return \Illuminate\Database\Eloquent\Collection
     */
    public function items()
    {
        return $this->belongsToMany(Item::class);
    }
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use App\Bitacora;
use App\Http\Requests\TagRequest;
use App\Tag;
use App\User;
use Carbon\Carbon;

class TagController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(User::class);
    }

    /**
     * Display a listing of the users
     *
     * @param \App\Tag $model
     * @return \Illuminate\View\View
     */

    public function index(Tag $model)
    {
        $this->authorize('manage-items', User::class);

        return view('tags.index', ['tags' => $model->all()]);
    }

    /*
  public function index(User $model)
  {
      $this->authorize('manage-users', User::class);

      return view('tags.index', ['tags' => $model->get()]);
  }

    /**
     * Show the form for creating a new tag
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        return view('tags.create');
    }

    /**
     * Store a newly created tag in storage
     *
     * @param \App\Http\Requests\TagRequest $request
     * @param \App\Tag $model
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(TagRequest $request, Tag $model)
    {
        $model->create($request->all());

        $user = auth()->user();

        $bitacora = new Bitacora();
        $bitacora->author = $user->name;
        $bitacora->action = "Crear Tag";
        $bitacora->created_at = Carbon::now();
        $bitacora->updated_at = Carbon::now();
        $bitacora->save();
        return redirect()->route('tag.index')->withStatus(__('Tag creado con éxito.'));
    }

    /**
     * Show the form for editing the specified tag
     *
     * @param \App\Tag $tag
     * @return \Illuminate\View\View
     */
    public function edit(Tag $tag)
    {
        return view('tags.edit', compact('tag'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \App\Http\Requests\TagRequest $request
     * @param \App\Tag $tag
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(TagRequest $request, Tag $tag)
    {
        $tag->update($request->all());
        $user = auth()->user();

        $bitacora = new Bitacora();
        $bitacora->author = $user->name;
        $bitacora->action = "Editar tag";
        $bitacora->created_at = Carbon::now();
        $bitacora->updated_at = Carbon::now();
        $bitacora->save();

        return redirect()->route('tag.index')->withStatus(__('Tag editado con éxito.'));
    }

    /**
     * Remove the specified tag from storage
     *
     * @param \App\Tag $tag
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Tag $tag)
    {
        if (!$tag->items->isEmpty()) {
            return redirect()->route('tag.index')->withErrors(__('Este tag tiene cursos indexados y no puede ser borrado.'));
        }

        $tag->delete();

        $user = auth()->user();

        $bitacora = new Bitacora();
        $bitacora->author = $user->name;
        $bitacora->action = "Eliminar tag";
        $bitacora->created_at = Carbon::now();
        $bitacora->updated_at = Carbon::now();
        $bitacora->save();
        return redirect()->route('tag.index')->withStatus(__('Tag borrado con éxito.'));
    }
}

resources/views/tags/create.blade.php
@extends('layouts.app', [
    'title' => __('Crear Tag'),
    'parentSection' => 'laravel',
    'elementName' => 'tag-management'
])

@section('content')
    @component('layouts.headers.auth')
        @component('layouts.headers.breadcrumbs')
            @slot('title')
                {{ __('Agregar Tag') }}
            @endslot

            <li class="breadcrumb-item"><a href="{{ route('tag.index') }}">{{ __('Agregar Tag') }}</a></li>
        @endcomponent
    @endcomponent

    <div class="container-fluid mt--6">
        <div class="row">
            <div class="col-xl-12 order-xl-1">
                <div class="card">
                    <div class="card-header">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Agregar Tag') }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('tag.index') }}"
                                   class="btn btn-sm btn-primary">{{ __('Regresar') }}</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{ route('tag.store') }}" autocomplete="off">
                            @csrf

                            <h6 class="heading-small text-muted mb-4">{{ __('Información del Tag') }}</h6>
                            <div class="pl-lg-4">
                                <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-name">{{ __('Nombre') }}</label>
                                    <input type="text" name="name" id="input-name"
                                           class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}"
                                           placeholder="{{ __('Nombre') }}" value="{{ old('name') }}" required
                                           autofocus>

                                    @include('alerts.feedback', ['field' => 'name'])
                                </div>

                                <div class="form-group{{ $errors->has('color') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-name">{{ __('Color') }}</label>
                                    <input type="color" name="color" id="input-name"
                                           class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}"
                                           placeholder="{{ __('Color') }}" value="{{ old('color') }}" required>

                                    @include('alerts.feedback', ['field' => 'color'])
                                </div>

                                <div class="text-center">
                                    <button type="submit" class="btn btn-success mt-4">{{ __('Guardar') }}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/tags/edit.blade.php
@extends('layouts.app', [
    'title' => __('Editar Tag'),
    'parentSection' => 'laravel',
    'elementName' => 'tag-management'
])

@section('content')
    @component('layouts.headers.auth')
        @component('layouts.headers.breadcrumbs')
            @slot('title')
                {{ __('Editar Tag') }}
            @endslot

            <li class="breadcrumb-item"><a href="{{ route('tag.index') }}">{{ __('Editar') }}</a></li>
        @endcomponent
    @endcomponent

    <div class="container-fluid mt--6">
        <div class="row">
            <div class="col-xl-12 order-xl-1">
                <div class="card">
                    <div class="card-header">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Editar Tag') }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('tag.index') }}"
                                   class="btn btn-sm btn-primary">{{ __('Regresar') }}</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{ route('tag.update', $tag) }}" autocomplete="off">
                            @csrf
                            @method('put')

                            <h6 class="heading-small text-muted mb-4">{{ __('Información del Tag') }}</h6>
                            <div class="pl-lg-4">
                                <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-name">{{ __('Nombre') }}</label>
                                    <input type="text" name="name" id="input-name"
                                           class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}"
                                           placeholder="{{ __('Nombre') }}" value="{{ old('name', $tag->name) }}"
                                           required autofocus>

                                    @include('alerts.feedback', ['field' => 'name'])
                                </div>
                                <div class="form-group{{ $errors->has('color') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-name">{{ __('Color') }}</label>
                                    <input type="color" name="color" id="input-name"
                                           class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}"
                                           placeholder="{{ __('Color') }}" value="{{ old('color', $tag->color) }}"
                                           required>

                                    @include('alerts.feedback', ['field' => 'color'])
                                </div>

                                <div class="text-center">
                                    <button type="submit" class="btn btn-success mt-4">{{ __('Editar') }}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/tags/index.blade.php
@extends('layouts.app', [
    'title' => __('Tags'),
    'parentSection' => 'laravel',
    'elementName' => 'tag-management'
])

@section('content')
    @component('layouts.headers.auth')
        @component('layouts.headers.breadcrumbs')
            @slot('title')
                {{ __('Tags') }}
            @endslot

            <li class="breadcrumb-item"><a href="{{ route('tag.index') }}">{{ __('Administrar Tags') }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ __('Lista') }}</li>
        @endcomponent
    @endcomponent

    <div class="container-fluid mt--6">
        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-header">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Tags') }}</h3>
                                <p class="text-sm mb-0">
                                    {{ __('Aquí puedes agregar y editar tags.') }}
                                </p>
                            </div>
                            @can('create', App\Tag::class)
                                <div class="col-4 text-right">
                                    <a href="{{ route('tag.create') }}"
                                       class="btn btn-sm btn-primary">{{ __('Agregar tag') }}</a>
                                </div>
                            @endcan
                        </div>
                    </div>

                    <div class="col-12 mt-2">
                        @include('alerts.success')
                        @include('alerts.errors')
                    </div>

                    <div class="table-responsive py-4">
                        <table class="table align-items-center table-flush" id="datatable-basic">
                            <thead class="thead-light">
                            <tr>
                                <th scope="col">{{ __('Nombre') }}</th>
                                <th scope="col">{{ __('Color') }}</th>
                                <th scope="col">{{ __('Fecha de creación') }}</th>
                                @can('manage-items', App\User::class)
                                    <th scope="col"></th>
                                @endcan
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($tags as $tag)
                                <tr>
                                    <td>{{ $tag->name }}</td>
                                    <td><span class="badge badge-default"
                                              style="background-color:{{ $tag->color }}">{{ $tag->name }}</span></td>
                                    <td>{{ $tag->created_at->format('d/m/Y H:i') }}</td>
                                    @can('manage-items', App\User::class)
                                        <td class="text-right">
                                            @if (auth()->user()->can('update', $tag) || auth()->user()->can('delete', $tag))
                                                <div class="dropdown">
                                                    <a class="btn btn-sm btn-icon-only text-light" href="#"
                                                       role="button" data-toggle="dropdown" aria-haspopup="true"
                                                       aria-expanded="false">
                                                        <i class="fas fa-ellipsis-v"></i>
                                                    </a>
                                                    <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                                        @can('update', $tag)
                                                            <a class="dropdown-item"
                                                               href="{{ route('tag.edit', $tag) }}">{{ __('Editar') }}</a>
                                                        @endcan
                                                        @if ($tag->items->isEmpty() && auth()->user()->can('delete', $tag))
                                                            <form action="{{ route('tag.destroy', $tag) }}"
                                                                  method="post">
                                                                @csrf
                                                                @method('delete')
                                                                <button type="button" class="dropdown-item"
                                                                        onclick="confirm('{{ __("¿Estás seguro que quieres eliminar este tag?") }}') ? this.parentElement.submit() : ''">
                                                                    {{ __('Eliminar') }}
                                                                </button>
                                                            </form>
                                                        @endif
                                                    </div>
                                                </div>
                                            @endif
                                        </td>
                                    @endcan
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        @include('layouts.footers.auth')
    </div>
@endsection

@push('css')
    <link rel="stylesheet" href="{{ asset('argon') }}/vendor/datatables.net-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="{{ asset('argon') }}/vendor/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css">
    <link rel="stylesheet" href="{{ asset('argon') }}/vendor/datatables.net-select-bs4/css/select.bootstrap4.min.css">
@endpush

@push('js')
    <script src="{{ asset('argon') }}/vendor/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="{{ asset('argon') }}/vendor/datatables.net-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="{{ asset('argon') }}/vendor/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="{{ asset('argon') }}/vendor/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js"></script>
    <script src="{{ asset('argon') }}/vendor/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="{{ asset('argon') }}/vendor/datatables.net-buttons/js/buttons.flash.min.js"></script>
    <script src="{{ asset('argon') }}/vendor/datatables.net-buttons/js/buttons.print.min.js"></script>
    <script src="{{ asset('argon') }}/vendor/datatables.net-select/js/dataTables.select.min.js"></script>
@endpush