routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
})->name('welcome');

Auth::routes();

Route::get('dashboard', 'HomeController@index')->name('home');

Route::resource('item_user', 'ItemUserController', ['except' => ['show']]);
Route::get('del_item_user', 'ItemUserController@del_item_user');
Route::get('item_user/{userId}', 'ItemUserController@show');
Route::get('users_progress', 'ItemUserController@progress');

Route::get('item/present/{itemId}', 'ItemController@present');
Route::get('item/present/{itemId}/{progress}', 'ItemUserController@store_progress');
Route::get('item/present/{itemId}/indexes/{indexes}', 'ItemUserController@store_indexes');

Route::get('item/create/activ/{itemId}', 'ItemController@activ');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('exams','ExamsContoller');

    Route::get('preguntas/{id}','QuestionController@index');
    Route::get('preguntas/create/{id}','QuestionController@create');
    Route::get('preguntas/edit/{exam_id}/{id}','QuestionController@edit');
    Route::post('preguntas/store/{id}','QuestionController@store');
    Route::put('preguntas/update/{exam_id}/{id}','QuestionController@update');
    Route::delete('preguntas/delete/{exam_id}/{id}','QuestionController@destroy');

    Route::resource('userExam','UserExamController');
    Route::resource('estadisticas','EstadisticasController');
    Route::get('exam/{exam_id}/{index}','UserExamController@examen');
    Route::post('next/{exam_id}/{index}','UserExamController@subir');
    Route::post('calificar/{examid}','UserExamController@calificar');
    Route::post('salvar/{examid}/{cali}','UserExamController@salvar_cali');

    Route::resource('/sendComentarios','ComentariosController');

    Route::resource('category', 'CategoryController', ['except' => ['show']]);
    Route::resource('tag', 'TagController', ['except' => ['show']]);
    Route::resource('item', 'ItemController', ['except' => ['show']]);
    Route::resource('path', 'PathController', ['except' => ['show']]);
    Route::resource('grades', 'GradesController', ['except' => ['show']]);
    Route::get('grades/{userid}', 'GradesController@grades');
    Route::resource('curso', 'CourseController', ['except' => ['show']]);
    Route::resource('role', 'RoleController', ['except' => ['show', 'destroy']]);
    Route::resource('user', 'UserController', ['except' => ['show']]);
    Route::resource('bitacora', 'BitacoraController', ['except' => ['show']]);
    Route::get('transcription/{itemId}', 'ItemController@transcription');
    Route::get('/transcription/slide/{itemId}', 'ItemController@slide');
    Route::post('/transcription/register/{itemId}', 'ItemController@create_slide_trans');
    Route::delete('/transcription/delete/{slideId}/{itemId}', 'ItemController@destroy_slide_transcription');
    Route::get('/transcription/edit/{itemId}/{slideId}', 'ItemController@update_show');
    Route::post('/transcription/update/{itemId}/{slideId}', 'ItemController@update_slide');
    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
    Route::get('{page}', ['as' => 'page.index', 'uses' => 'PageController@index']);


});

app/ItemUser.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ItemUser extends Model
{
    //
    protected $table = 'item_user';

    protected $casts = [
        'indexes' => 'array'
    ];

}

app/Http/Controllers/ItemUserController.php
<?php

namespace App\Http\Controllers;

use App\Bitacora;
use App\Item;
use App\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class ItemUserController extends Controller
{

    /**
     * Display a listing of the users
     *
     * @param \App\User $model
     * @param \App\Item $model2
     * @return \Illuminate\View\View
     */
    public function index(User $model, Item $model2)
    {
        $this->authorize('manage-users', User::class);
        return view('item_user.index', ['users' => $model->with('role')->get(), 'items' => $model2->get()]);
    }

    public function del_item_user(User $model, Item $model2)
    {
        $this->authorize('manage-users', User::class);
        return view('item_user.remove', ['users' => $model->with('role')->get(), 'items' => $model2->get()]);
    }

    /**
     * Display a listing of the items
     *
     * @param \App\Item $model
     * @return \Illuminate\View\View
     */
    public function progress(Item $model)
    {
        $user = Auth::user();
        if ($user->role_id == 1) {
            return view('item_user.progress', ['items' => $model
                ->with('tags')
                ->join('item_user', 'item_user.item_id', '=', 'items.id')
                ->join('users', 'item_user.user_id', '=', 'users.id')
                ->join('categories', 'items.category_id', '=', 'categories.id')
                ->select('users.email as user_email', 'items.name as item_name', 'item_user.*', 'categories.name as category')
                ->get()
            ]);
        } else {
            abort(403, 'Unauthorized action.');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = User::find(request('user_select'));
        $selected_items = request('items');
        $all_items = DB::table('items')->select('id')->get()->pluck('id')->toArray();
        $unselected_items = [];

        if ($selected_items && $all_items) {
            $unselected_items = array_diff($all_items, $selected_items);

            foreach ($selected_items as $item) {
                //Check if the user already has the item asigned
                $exists = DB::table('item_user')->where([['item_id', '=', $item], ['user_id', '=', $user->id]])->first();
                //If it does not have it asigned, create that relation int he pivot table
                if (!$exists) {
                    $user->items()->attach($item, array('progress' => 0, 'indexes' => '[0,0,0]', 'assigned' => true));
                } else {
                    $user->items()->updateExistingPivot($item, array('assigned' => true));
                }
            }

            foreach ($unselected_items as $item) {
                //Check if the user already has one of the unselected items asigned
                $exists = DB::table('item_user')->where([['item_id', '=', $item], ['user_id', '=', $user->id]])->first();
                //If it does have it asigned, update that relation an change assigned to false
                if ($exists) {
                    $user->items()->updateExistingPivot($item, array('assigned' => false));
                }
            }

            $user = auth()->user();

            $bitacora = new Bitacora();
            $bitacora->author = $user->name;
            $bitacora->action = "Asignar curso a alumno";
            $bitacora->created_at = Carbon::now();
            $bitacora->updated_at = Carbon::now();
            $bitacora->save();

            return back()->withStatus(__('Los cursos han sido asignados con éxito.'));

        } else {
            return back()->withErrors(__('No seleccionaste ningún curso para el usuario'));
        }

    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $items_user = DB::table('item_user')
            ->join('items', 'item_user.item_id', '=', 'items.id')
            ->where([['user_id', '=', $id], ['assigned', '=', true]])
            ->get('items.id');
        $array_items_user = [];
        foreach ($items_user as $item_user) {
            $aux = json_encode($item_user);
            array_push($array_items_user, $aux);
        }
        return $array_items_user;
    }

    /**
     * Display the specified resource.
     *
     * @param int $item_id
     * @param int $progress
     * @return \Illuminate\Http\Response
     */
    public function store_progress($item_id, $progress)
    {
        $user = Auth::user();
        $user->items()->updateExistingPivot($item_id, array('progress' => $progress));
        return "success";
    }

    /**
     * Display the specified resource.
     *
     * @param int $item_id
     * @param string $indexes
     * @return \Illuminate\Http\Response
     */
    public function store_indexes($item_id, $indexes)
    {
        $user = Auth::user();
        $user->items()->updateExistingPivot($item_id, array('indexes' => $indexes));
        return "success";
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/item_user/index.blade.php
@extends('layouts.app', [
    'title' => __('Asignar Cursos'),
    'navClass' => 'bg-default',
    'parentSection' => 'item_user-management',
    'elementName' => 'item_user-management'
])

@section('content')
    @include('forms.header', [
        'title' => __('Asignar Cursos'),
        'description' => __('Aquí puedes asignar cursos a los usuarios'),
        'class' => 'col-lg-7'
])

    <div class="container-fluid mt--6">
        <div class="row">
            <div class="col-xl-4 order-xl-2">
                <!-- Progress track -->
            </div>
            <div class="col-xl-10 order-xl-1">
                <div class="card">
                    <div class="card-header">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Asignar cursos') }}</h3>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{ route('item_user.store') }}" autocomplete="off">
                            @csrf

                            <h6 class="heading-small text-muted mb-4">{{ __('Usuario') }}</h6>

                            @include('alerts.success')
                            @include('alerts.errors')
                            <div class="pl-lg-4">

                                <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="user">{{ __('Usuario') }}</label>
                                    <select class="form-control" data-toggle="select" title="Simple select"
                                            data-live-search="true" data-live-search-placeholder="Busca ..."
                                            name="user_select" id="user_select">
                                        @foreach ($users as $user)
                                            <option value="{{ $user->id }}">{{ $user->email }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="form-group{{ $errors->has('email') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="items">{{ __('Cursos') }}</label>
                                    <select class="form-control" data-toggle="select" multiple multiple="multiple"
                                            data-placeholder="Selecciona los cursos del usuario" name="items[]"
                                            id="items_select">
                                        @foreach ($items as $item)
                                            <option value="{{ $item->id }}">{{ $item->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="text-center">
                                    <button type="submit"
                                            class="btn btn-success mt-4">{{ __('Asignar cursos') }}</button>
                                </div>

                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/item_user/progress.blade.php
@extends('layouts.app', [
    'title' => __('Progreso de los usuarios'),
    'parentSection' => 'users_progress-management',
    'elementName' => 'users_progress-management'
])

@section('content')
    @component('layouts.headers.auth')
        @component('layouts.headers.breadcrumbs')
            @slot('title')
                {{ __('Progreso de los usuarios') }}
            @endslot

            <li class="breadcrumb-item"><a href="{{ route('item.index') }}">{{ __('Progreso de los usuarios') }}</a>
            </li>
        @endcomponent
    @endcomponent

    <div class="container-fluid mt--6">
        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-header">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Progreso de los usuarios') }}</h3>
                                <p class="text-sm mb-0">
                                    {{ __('Aquí puedes ver el progreso de los usuarios en cada uno de sus cursos.') }}
                                </p>
                            </div>
                        </div>
                    </div>

                    <div class="col-12 mt-2">
                        @include('alerts.success')
                        @include('alerts.errors')
                    </div>

                    <div class="table-responsive py-4">
                        <table class="table align-items-center table-flush" id="datatable-basic">
                            <thead class="thead-light">
                            <tr>
                                <th scope="col">{{ __('Usuario') }}</th>
                                <th scope="col">{{ __('Curso') }}</th>
                                @can('manage-items', App\User::class)
                                    <th scope="col">{{ __('Progreso') }}</th>
                                @endcan
                                <th scope="col">{{ __('Asignación') }}</th>

                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($items as $item)
                                <tr>
                                    <td>{{ $item->user_email }}</td>
                                    <td>{{ $item->item_name }}</td>


                                    @can('manage-items', App\User::class)
                                        <td>
                                            <div class="progress-info">
                                                <div class="progress-percentage">
                                                    <span>{{ $item->progress }}%</span>
                                                </div>
                                                @if ($item->progress < 100)
                                                    <div class="progress-label">
                                                        <span>No terminado</span>
                                                    </div>
                                                @else
                                                    <div class="progress-label">
                                                        <span style="color:#4dc96e">Terminado</span>
                                                    </div>
                                                @endif
                                            </div>
                                            <div class="progress">
                                                <div class="progress-bar bg-info" role="progressbar"
                                                     aria-valuenow="{{$item->progress}}" aria-valuemin="0"
                                                     aria-valuemax="100" style="width: {{$item->progress}}%;"></div>
                                            </div>
                                        </td>
                                    @endcan

                                    @if ($item->assigned)
                                        <td>Asignado</td>
                                    @else
                                        <td>No asignado</td>
                                    @endif

                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        @include('layouts.footers.auth')
    </div>
@endsection

@push('css')
    <link rel="stylesheet" href="{{ asset('argon') }}/vendor/datatables.net-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="{{ asset('argon') }}/vendor/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css">
    <link rel="stylesheet" href="{{ asset('argon') }}/vendor/datatables.net-select-bs4/css/select.bootstrap4.min.css">
@endpush

@push('js')
    <script src="{{ asset('argon') }}/vendor/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="{{ asset('argon') }}/vendor/datatables.net-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="{{ asset('argon') }}/vendor/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="{{ asset('argon') }}/vendor/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js"></script>
    <script src="{{ asset('argon') }}/vendor/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="{{ asset('argon') }}/vendor/datatables.net-buttons/js/buttons.flash.min.js"></script>
    <script src="{{ asset('argon') }}/vendor/datatables.net-buttons/js/buttons.print.min.js"></script>
    <script src="{{ asset('argon') }}/vendor/datatables.net-select/js/dataTables.select.min.js"></script>
@endpush

resources/views/item_user/remove.blade.php
@extends('layouts.app', [
    'title' => __('Asignar Cursos'),
    'navClass' => 'bg-default',
    'parentSection' => 'item_user-management',
    'elementName' => 'item_user-management'
])

@section('content')
    @include('forms.header', [
        'title' => __('Asignar Cursos'),
        'description' => __('Aquí puedes desasignar cursos a los usuarios'),
        'class' => 'col-lg-7'
])

    <div class="container-fluid mt--6">
        <div class="row">
            <div class="col-xl-4 order-xl-2">
                <!-- Progress track -->
            </div>
            <div class="col-xl-10 order-xl-1">
                <div class="card">
                    <div class="card-header">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Desasignar cursos') }}</h3>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="" autocomplete="off">
                            @csrf

                            <h6 class="heading-small text-muted mb-4">{{ __('Usuario') }}</h6>

                            @include('alerts.success')
                            @include('alerts.errors')
                            <div class="pl-lg-4">

                                <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="user">{{ __('Usuario') }}</label>
                                    <select class="form-control" data-toggle="select" title="Simple select"
                                            data-live-search="true" data-live-search-placeholder="Busca ..."
                                            name="user_select" id="user_select">
                                        @foreach ($users as $user)
                                            <option value="{{ $user->id }}">{{ $user->email }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="form-group{{ $errors->has('email') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="items">{{ __('Cursos') }}</label>
                                    <select class="form-control" data-toggle="select" multiple multiple="multiple"
                                            data-placeholder="Selecciona los cursos del usuario" name="items[]"
                                            id="items_select">
                                        @foreach ($items as $item)
                                            <option value="{{ $item->id }}">{{ $item->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="text-center">
                                    <button type="submit"
                                            class="btn btn-danger mt-4">{{ __('Remover cursos') }}</button>
                                </div>

                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        @include('layouts.footers.auth')
    </div>
@endsection