routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
})->name('welcome');

Auth::routes();

Route::get('dashboard', 'HomeController@index')->name('home');

Route::resource('item_user', 'ItemUserController', ['except' => ['show']]);
Route::get('del_item_user', 'ItemUserController@del_item_user');
Route::get('item_user/{userId}', 'ItemUserController@show');
Route::get('users_progress', 'ItemUserController@progress');

Route::get('item/present/{itemId}', 'ItemController@present');
Route::get('item/present/{itemId}/{progress}', 'ItemUserController@store_progress');
Route::get('item/present/{itemId}/indexes/{indexes}', 'ItemUserController@store_indexes');

Route::get('item/create/activ/{itemId}', 'ItemController@activ');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('exams','ExamsContoller');

    Route::get('preguntas/{id}','QuestionController@index');
    Route::get('preguntas/create/{id}','QuestionController@create');
    Route::get('preguntas/edit/{exam_id}/{id}','QuestionController@edit');
    Route::post('preguntas/store/{id}','QuestionController@store');
    Route::put('preguntas/update/{exam_id}/{id}','QuestionController@update');
    Route::delete('preguntas/delete/{exam_id}/{id}','QuestionController@destroy');

    Route::resource('userExam','UserExamController');
    Route::resource('estadisticas','EstadisticasController');
    Route::get('exam/{exam_id}/{index}','UserExamController@examen');
    Route::post('next/{exam_id}/{index}','UserExamController@subir');
    Route::post('calificar/{examid}','UserExamController@calificar');
    Route::post('salvar/{examid}/{cali}','UserExamController@salvar_cali');

    Route::resource('/sendComentarios','ComentariosController');

    Route::resource('category', 'CategoryController', ['except' => ['show']]);
    Route::resource('tag', 'TagController', ['except' => ['show']]);
    Route::resource('item', 'ItemController', ['except' => ['show']]);
    Route::resource('path', 'PathController', ['except' => ['show']]);
    Route::resource('grades', 'GradesController', ['except' => ['show']]);
    Route::get('grades/{userid}', 'GradesController@grades');
    Route::resource('curso', 'CourseController', ['except' => ['show']]);
    Route::resource('role', 'RoleController', ['except' => ['show', 'destroy']]);
    Route::resource('user', 'UserController', ['except' => ['show']]);
    Route::resource('bitacora', 'BitacoraController', ['except' => ['show']]);
    Route::get('transcription/{itemId}', 'ItemController@transcription');
    Route::get('/transcription/slide/{itemId}', 'ItemController@slide');
    Route::post('/transcription/register/{itemId}', 'ItemController@create_slide_trans');
    Route::delete('/transcription/delete/{slideId}/{itemId}', 'ItemController@destroy_slide_transcription');
    Route::get('/transcription/edit/{itemId}/{slideId}', 'ItemController@update_show');
    Route::post('/transcription/update/{itemId}/{slideId}', 'ItemController@update_slide');
    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
    Route::get('{page}', ['as' => 'page.index', 'uses' => 'PageController@index']);


});

app/Http/Controllers/EstadisticasController.php
<?php

namespace App\Http\Controllers;

use App\Item;
use App\ItemUser;
use App\User;
use Illuminate\Http\Request;

class EstadisticasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $users_count = User::count();
        $Items_count = Item::count();
        $item_users = ItemUser::get();
        $promedioPromedio = User::get();

        $terminados = 0;

        $Pexamenes = 0;
        $i = 0;

        foreach ($promedioPromedio as $promedio){
            $Pexamenes += $promedio->promedio;
            if(($promedio->promedio)!=0){
                $i++;
            }

            $usrs = ItemUser::where('user_id',$promedio->id)->get();
            $j = 0;

            foreach ($usrs as $usr){
                if(($usr->exam_score)>= 60){
                    $j++;
                }
            }

            if($j == 8){
                $terminados++;
            }

        }

        if($i != 0){
            $Pexamenes = $Pexamenes/$i;
        }

        return view('estadisticas.index',['users_count' => $users_count, 'item_count' => $Items_count,'promedio'=>$Pexamenes,'terminados'=>$terminados]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/estadisticas/index.blade.php
@extends('layouts.app', [
    'title' => __('Calificaciones'),
    'parentSection' => 'grades-management',
    'elementName' => 'grades-management'
])

@section('content')
    @component('layouts.headers.auth')
        @component('layouts.headers.breadcrumbs')
            @slot('title')
                {{ __('Estadisticas') }}
            @endslot
            <li class="breadcrumb-item"><a href="{{ route('user.index') }}">{{ __('Calificaciones usuarios') }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ __('Lista') }}</li>
        @endcomponent
    @endcomponent

    <div class="container-fluid mt--6">
        <div class="row">
            <div class="col">
                <div class="card">

                    <div class="card-header">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Estadisticas') }}</h3>
                                <p class="text-sm mb-0">
                                    {{ __('Aquí puedes ver tus estadisticas.') }}
                                </p>
                            </div>
                        </div>
                    </div>

                    <div class="col-12 mt-2">
                        @include('alerts.success')
                        @include('alerts.errors')
                    </div>

                    <div class="row">
                        <div class="col-sm-4">
                            <div style="width: 18rem;">
                                <a href="{{ route('item.index') }}">
                                    <div class="card card-stats mb-4 mb-lg-0">
                                        <div class="card-body">
                                            <div class="row">
                                                <div class="col">
                                                    <h5 class="card-title text-uppercase text-muted mb-0">Numero de cursos activos</h5>
                                                    <span class="h2 font-weight-bold mb-0">1</span>
                                                </div>
                                                <div class="col-auto">
                                                    <div class="icon icon-shape bg-xofluza text-white rounded-circle shadow">
                                                        <i class="fas fa-chart-bar"></i>
                                                    </div>
                                                    <br><br>
                                                </div>

                                            </div>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div style="width: 18rem;">
                                <a href="{{ route('user.index') }}">
                                    <div class="card card-stats mb-4 mb-lg-0">
                                        <div class="card-body">
                                            <div class="row">
                                                <div class="col">
                                                    <h5 class="card-title text-uppercase text-muted mb-0">Numero de alumnos</h5>
                                                    <span class="h2 font-weight-bold mb-0">{{$users_count}}</span>
                                                </div>
                                                <div class="col-auto">
                                                    <div class="icon icon-shape bg-xofluza text-white rounded-circle shadow">
                                                        <i class="fas fa-user"></i>
                                                    </div>
                                                    <br><br>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div style="width: 18rem;">
                                <a href="{{ route('grades.index') }}">
                                    <div class="card card-stats mb-4 mb-lg-0">
                                        <div class="card-body">
                                            <div class="row">
                                                <div class="col">
                                                    <h5 class="card-title text-uppercase text-muted mb-0">Numero de certificados</h5>
                                                    <span class="h2 font-weight-bold mb-0">1</span>
                                                </div>
                                                <div class="col-auto">
                                                    <div class="icon icon-shape bg-xofluza text-white rounded-circle shadow">
                                                        <i class="fas fa-chart-bar">{{$terminados}}</i>
                                                    </div>

                                                </div>

                                            </div>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>

                    </div>
                    <br><br><br><br><br>



                </div>

            </div>

        </div>

        @include('layouts.footers.auth')
    </div>
@endsection

@push('css')
    <link rel="stylesheet" href="{{ asset('argon') }}/vendor/datatables.net-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="{{ asset('argon') }}/vendor/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css">
    <link rel="stylesheet" href="{{ asset('argon') }}/vendor/datatables.net-select-bs4/css/select.bootstrap4.min.css">
@endpush

@push('js')
    <script src="{{ asset('argon') }}/vendor/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="{{ asset('argon') }}/vendor/datatables.net-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="{{ asset('argon') }}/vendor/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="{{ asset('argon') }}/vendor/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js"></script>
    <script src="{{ asset('argon') }}/vendor/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="{{ asset('argon') }}/vendor/datatables.net-buttons/js/buttons.flash.min.js"></script>
    <script src="{{ asset('argon') }}/vendor/datatables.net-buttons/js/buttons.print.min.js"></script>
    <script src="{{ asset('argon') }}/vendor/datatables.net-select/js/dataTables.select.min.js"></script>
@endpush