routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
})->name('welcome');

Auth::routes();

Route::get('dashboard', 'HomeController@index')->name('home');

Route::resource('item_user', 'ItemUserController', ['except' => ['show']]);
Route::get('del_item_user', 'ItemUserController@del_item_user');
Route::get('item_user/{userId}', 'ItemUserController@show');
Route::get('users_progress', 'ItemUserController@progress');

Route::get('item/present/{itemId}', 'ItemController@present');
Route::get('item/present/{itemId}/{progress}', 'ItemUserController@store_progress');
Route::get('item/present/{itemId}/indexes/{indexes}', 'ItemUserController@store_indexes');

Route::get('item/create/activ/{itemId}', 'ItemController@activ');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('exams','ExamsContoller');

    Route::get('preguntas/{id}','QuestionController@index');
    Route::get('preguntas/create/{id}','QuestionController@create');
    Route::get('preguntas/edit/{exam_id}/{id}','QuestionController@edit');
    Route::post('preguntas/store/{id}','QuestionController@store');
    Route::put('preguntas/update/{exam_id}/{id}','QuestionController@update');
    Route::delete('preguntas/delete/{exam_id}/{id}','QuestionController@destroy');

    Route::resource('userExam','UserExamController');
    Route::resource('estadisticas','EstadisticasController');
    Route::get('exam/{exam_id}/{index}','UserExamController@examen');
    Route::post('next/{exam_id}/{index}','UserExamController@subir');
    Route::post('calificar/{examid}','UserExamController@calificar');
    Route::post('salvar/{examid}/{cali}','UserExamController@salvar_cali');

    Route::resource('/sendComentarios','ComentariosController');

    Route::resource('category', 'CategoryController', ['except' => ['show']]);
    Route::resource('tag', 'TagController', ['except' => ['show']]);
    Route::resource('item', 'ItemController', ['except' => ['show']]);
    Route::resource('path', 'PathController', ['except' => ['show']]);
    Route::resource('grades', 'GradesController', ['except' => ['show']]);
    Route::get('grades/{userid}', 'GradesController@grades');
    Route::resource('curso', 'CourseController', ['except' => ['show']]);
    Route::resource('role', 'RoleController', ['except' => ['show', 'destroy']]);
    Route::resource('user', 'UserController', ['except' => ['show']]);
    Route::resource('bitacora', 'BitacoraController', ['except' => ['show']]);
    Route::get('transcription/{itemId}', 'ItemController@transcription');
    Route::get('/transcription/slide/{itemId}', 'ItemController@slide');
    Route::post('/transcription/register/{itemId}', 'ItemController@create_slide_trans');
    Route::delete('/transcription/delete/{slideId}/{itemId}', 'ItemController@destroy_slide_transcription');
    Route::get('/transcription/edit/{itemId}/{slideId}', 'ItemController@update_show');
    Route::post('/transcription/update/{itemId}/{slideId}', 'ItemController@update_slide');
    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
    Route::get('{page}', ['as' => 'page.index', 'uses' => 'PageController@index']);


});

app/Item.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class Item extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'excerpt', 'description', 'url', 'bibliografia', 'picture','picture2' ,'category_id', 'status', 'date', 'show_on_homepage', 'options','exam_id'
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'options' => 'array',
    ];

    /**
     * Get the category of the item
     *
     * @return \App\Category
     */
    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    /**
     * Get the tags of the item
     *
     * @return \Illuminate\Database\Eloquent\Collection
     */
    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

    /**
     * Get the path to the picture
     *
     * @return string
     */
    public function path()
    {
        return "/storage/{$this->picture}";
    }

    public function users()
    {
        return $this->belongsToMany(User::class)->withPivot(['item_id', 'user_id', 'progress', 'indexes', 'assigned']);
    }

    public function current_user_items()
    {
        return $this->belongsToMany(User::class)->withPivot(['item_id', 'user_id', 'progress', 'indexes', 'assigned'])
            ->wherePivot('user_id', '=', Auth::id());
    }

    public function exam()
    {
        return $this->belongsTo('App\Exam');
    }

}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use App\Bitacora;
use App\Category;
use App\Http\Requests\ItemRequest;
use App\Item;
use App\items_transcription;
use App\Tag;
use Carbon\Carbon;
use DB;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ItemController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Item::class);
    }

    /*
     * Funcion para acutlaizar una transcripcion de Slide
     */
    public function update_slide(Request $request, $itemId, $slideId)
    {

        $this->validate($request, [
            'slideNo' => 'required|integer',
            'transcription' => '',
        ]);

        $slide = items_transcription::find($slideId);
        $slide->slideNo = $request->input('slideNo');
        $slide->item_id = $itemId;
        $slide->transcription = $request->input('transcription');
        if($request->audio == null){
            $slide->audio = $request->audio_aux;
        }else{
            $slide->audio = $request->audio->store('audio', 'public');
        }

        $slide->created_at = Carbon::now();
        $slide->updated_at = Carbon::now();
        $slide->save();

        $user = auth()->user();

        $bitacora = new Bitacora();
        $bitacora->author = $user->name;
        $bitacora->action = "Editar transcripcion de slide";
        $bitacora->created_at = Carbon::now();
        $bitacora->updated_at = Carbon::now();
        $bitacora->save();

        return redirect('/transcription/' . $itemId)->withStatus(__('Transcripcion de slide editada con éxito.'));
    }

    /*
     * Funcion para mostrar una transcripcion de slide
     */
    public function update_show($itemId, $slideId, Item $model, items_transcription $trans)
    {
        return view('items.edit_transcription_slide', ['item' => $model->with(['tags', 'category'])->where('id', '=', $itemId)->get()->first()], ['trans' => $trans->where('id', '=', $slideId)->get()->first()]);
    }

    /*
     * Funcion mostrar el conenido de todas las slides
     */
    public function slide($id, Item $model)
    {
        return view('items.item_transcription', ['item' => $model->with(['tags', 'category'])->where('id', '=', $id)->get()->first()]);
    }

    /*
     * Funcion para mostrar
     */
    public function transcription($id, Item $model, items_transcription $trans)
    {

        return view('items.transcription', ['item' => $model->with(['tags', 'category'])->where('id', '=', $id)->get()->first()],
            ['trans' => $trans->where('item_id', '=', $id)->get()]);
    }

    /**
     * Display a listing of the items
     *
     * @param \App\Item $model
     * @return \Illuminate\View\View
     */
    public function index(Item $model)
    {
        $user = Auth::user();
        if ($user->role_id == 1 || $user->role_id == 2) {
            return view('items.index', ['items' => $model->with(['tags', 'category', 'users'])->get()]);
        } else {
            return view('items.index', ['items' => $model->whereHas('users', function ($query) use ($user) {
                $query->where([['user_id', $user->id], ['assigned', true]]);
            })->with('tags', 'category', 'current_user_items')->get()]);

        }
        //return view('items.index', ['items' => $model->with(['tags', 'category'])->get()]);
    }

    /**
     * Show the form for creating a new item
     *
     * @param \App\Tag $tagModel
     * @param \App\Category $categoryModel
     * @return \Illuminate\View\View
     */
    public function create(Tag $tagModel, Category $categoryModel, Item $model)
    {
        return view('items.create', [
            'tags' => $tagModel->get(['id', 'name']),
            'categories' => $categoryModel->get(['id', 'name',])
        ]);
    }

    /**
     * Store a newly created item in storage
     *
     * @param \App\Http\Requests\ItemRequest $request
     * @param \App\Item $model
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(ItemRequest $request, Item $model)
    {
        $item = $model->create($request->merge([
            'picture' => $request->photo->store('pictures', 'public'),
            'show_on_homepage' => $request->show_on_homepage ? 1 : 0,
            'options' => $request->options ? $request->options : null,
            'exam_id'=> 1,
            'date' => $request->date ? Carbon::parse($request->date)->format('Y-m-d') : null
        ])->all());

        $item->tags()->sync($request->get('tags'));

        $user = auth()->user();

        $bitacora = new Bitacora();
        $bitacora->author = $user->name;
        $bitacora->action = "Crear Presentacion";
        $bitacora->created_at = Carbon::now();
        $bitacora->updated_at = Carbon::now();
        $bitacora->save();

        return redirect()->route('item.index')->withStatus(__('Curso creado con éxito.'));
    }

    /**
     * Show the form for editing the specified item
     *
     * @param \App\Item $item
     * @param \App\Tag $tagModel
     * @param \App\Category $categoryModel
     * @return \Illuminate\View\View
     */
    public function edit(Item $item, Tag $tagModel, Category $categoryModel)
    {
        return view('items.edit', [
            'item' => $item->load('tags'),
            'tags' => $tagModel->get(['id', 'name']),
            'categories' => $categoryModel->get(['id', 'name'])
        ]);
    }


    /**
     * Update the specified resource in storage.
     *
     * @param \App\Http\Requests\Itemuest $request
     * @param \App\Item $item
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(ItemRequest $request, Item $item)
    {
        $item->update(
            $request->merge([
                'picture' => $request->photo ? $request->photo->store('pictures', 'public') : null,
                'picture2' => $request->photo2 ? $request->photo2->store('pictures', 'public') : null,
                'show_on_homepage' => $request->show_on_homepage ? 1 : 0,
                'options' => $request->options ? $request->options : null,
                'date' => $request->date ? Carbon::parse($request->date)->format('Y-m-d') : null
            ])->except([$request->hasFile('photo') ? '' : 'picture'])
        );

        $item->tags()->sync($request->get('tags'));

        $user = auth()->user();

        $bitacora = new Bitacora();
        $bitacora->author = $user->name;
        $bitacora->action = "Editar presentacion";
        $bitacora->created_at = Carbon::now();
        $bitacora->updated_at = Carbon::now();
        $bitacora->save();

        return redirect()->route('item.index')->withStatus(__('Curso editado con éxito.'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Item $item
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Item $item)
    {

        $delete = DB::table('item_user')->where('item_id', '=', $item->id)->delete();

        $item->delete();

        $user = auth()->user();

        $bitacora = new Bitacora();
        $bitacora->author = $user->name;
        $bitacora->action = "Elminar presentacion";
        $bitacora->created_at = Carbon::now();
        $bitacora->updated_at = Carbon::now();
        $bitacora->save();


        return redirect()->route('item.index')->withStatus(__('Curso borrado con éxito.'));
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @param \App\Item $model
     * @return \Illuminate\View\View
     */
    public function present($id, Item $model, items_transcription $transcription)
    {
        $user = Auth::user();
        if ($user->role_id == 1 || $user->role_id == 2) {
            return view('items.item_presentation', ['item' => $model->with(['tags', 'category'])->where('id', '=', $id)->get()->first()], ['tanscription' => $transcription->where('item_id', '=', $id)->get()]);
        } else {
            return view('items.item_presentation', ['item' => $model->with(['tags', 'category'])->join('item_user', 'item_user.item_id', '=', 'items.id')
                ->where([
                    ['item_user.item_id', '=', $id],
                    ['item_user.user_id', '=', $user->id],
                    ['item_user.assigned', '=', true]
                ])->get()->first()],['tanscription' => $transcription->where('item_id', '=', $id)->get()]);
        }
    }

    public function create_slide_trans(Request $request, $itemId)
    {
        $this->validate($request, [
            'slideNo' => 'required|integer',
            'transcription' => '',
        ]);

        $slide = new items_transcription();
        $slide->slideNo = $request->input('slideNo');
        $slide->item_id = $itemId;
        $slide->transcription = $request->input('transcription');
        if($request->audio == null){
            $slide->audio = null;
        }else{
            $slide->audio = $request->audio->store('audio', 'public');
        }

        $slide->created_at = Carbon::now();
        $slide->updated_at = Carbon::now();
        $slide->save();

        $user = auth()->user();

        $bitacora = new Bitacora();
        $bitacora->author = $user->name;
        $bitacora->action = "Crear Transcripcion ";
        $bitacora->created_at = Carbon::now();
        $bitacora->updated_at = Carbon::now();
        $bitacora->save();

        return redirect('/transcription/' . $itemId)->withStatus(__('Transcripcion de slide creada con éxito.'));
    }

    public function destroy_slide_transcription($slideId, $itemId)
    {

        $slide = items_transcription::find($slideId);
        $slide->delete();
        $user = auth()->user();

        $bitacora = new Bitacora();
        $bitacora->author = $user->name;
        $bitacora->action = "Eliminar transcripcion";
        $bitacora->created_at = Carbon::now();
        $bitacora->updated_at = Carbon::now();
        $bitacora->save();

resources/views/items/index.blade.php
@extends('layouts.app', [
    'title' => __('Cursos'),
    'parentSection' => 'laravel',
    'elementName' => 'item-management'
])

@section('content')

    @if (auth()->user()->can('create', App\Item::class))
        <br><br><br><br><br>
        <div class="container-fluid mt--6">
            <div class="row">
                <div class="col">
                    <div class="card">
                        <div class="card-header">
                            <div class="row align-items-center">
                                <div class="col-8">
                                    <h3 class="mb-0">{{ __('Cursos') }}</h3>
                                    <p class="text-sm mb-0">
                                        {{ __('Aquí puedes agregar y editar tus cursos.') }}
                                    </p>
                                </div>
                                @if (auth()->user()->can('create', App\Item::class))
                                    <div class="col-4 text-right">
                                        <a href="{{ route('item.create') }}"
                                           class="btn btn-sm btn-primary">{{ __('Agregar curso') }}</a>
                                    </div>
                                @endif
                            </div>
                        </div>

                        <div class="col-12 mt-2">
                            @include('alerts.success')
                            @include('alerts.errors')
                        </div>

                        <div class="table-responsive py-4">
                            <table class="table align-items-center table-flush" id="datatable-basic">
                                <thead class="thead-light">
                                <tr>
                                    <th scope="col">{{ __('Nombre') }}</th>
                                    <th scope="col">{{ __('Categoría') }}</th>
                                    @cannot('manage-items', App\User::class)
                                        <th scope="col">{{ __('Progreso') }}</th>
                                    @endcannot
                                    <th scope="col">{{ __('Imagen') }}</th>
                                    @can('manage-items', App\User::class)
                                        <th scope="col">{{ __('Ultima modificación') }}</th>
                                    @endcan
                                    @can('manage-items', App\User::class)
                                        <th scope="col"></th>
                                    @endcan
                                </tr>
                                </thead>
                                <tbody>
                                @foreach ($items as $item)
                                    <tr>
                                        <td style="width:30%;">
                                            <div style='width:20em; overflow:hidden;'><a
                                                    href="item/present/{{ $item->id }}">{{ $item->name }}</a></div>
                                        </td>
                                        <td>{{ $item->category->name }}</td>

                                        @cannot('manage-items', App\User::class)
                                            <td>
                                                <div class="progress-info">
                                                    <div class="progress-percentage">
                                                        <span>{{ $item->current_user_items[0]->pivot->progress }}%</span>
                                                    </div>
                                                    @if ($item->current_user_items[0]->pivot->progress < 100)
                                                        <div class="progress-label">
                                                            <span>No terminado</span>
                                                        </div>
                                                    @else
                                                        <div class="progress-label">
                                                            <span>Terminado</span>
                                                        </div>
                                                    @endif
                                                </div>
                                                <div class="progress">
                                                    <div class="progress-bar bg-info" role="progressbar"
                                                         aria-valuenow="{{ $item->current_user_items[0]->pivot->progress }}"
                                                         aria-valuemin="0" aria-valuemax="100"
                                                         style="width: {{ $item->current_user_items[0]->pivot->progress }}%;"></div>
                                                </div>
                                            </td>
                                        @endcannot

                                        <td>
                                            <img src="{{ $item->path() }}" alt="" style="max-width: 200px;">
                                        </td>
                                        @can('manage-items', App\User::class)
                                            <td>{{ $item->updated_at->format('d/m/Y H:i') }}</td>
                                        @endcan
                                        @can('manage-items', App\User::class)
                                            <td class="text-right">
                                                @if (auth()->user()->can('update', $item) || auth()->user()->can('delete', $item))
                                                    <div class="dropdown">
                                                        <a class="btn btn-sm btn-icon-only text-light" href="#"
                                                           role="button" data-toggle="dropdown" aria-haspopup="true"
                                                           aria-expanded="false">
                                                            <i class="fas fa-ellipsis-v"></i>
                                                        </a>
                                                        <div
                                                            class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                                            @can('update', $item)
                                                                <a class="dropdown-item"
                                                                   href="{{ route('item.edit', $item) }}">{{ __('Editar') }}</a>
                                                                <a class="dropdown-item"
                                                                   href="/transcription/{{$item->id}}">{{ __('Transcripcion') }}</a>
                                                            @endcan
                                                            @can('delete', $item)
                                                                <form action="{{ route('item.destroy', $item) }}"
                                                                      method="post">
                                                                    @csrf
                                                                    @method('delete')
                                                                    <button type="button" class="dropdown-item"
                                                                            onclick="confirm('{{ __("¿Estás seguro de que quieres eliminar este curso?") }}') ? this.parentElement.submit() : ''">
                                                                        {{ __('Eliminar') }}
                                                                    </button>
                                                                </form>
                                                            @endcan
                                                        </div>
                                                    </div>
                                                @endif
                                            </td>
                                        @endcan
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

            @include('layouts.footers.auth')
        </div>

    @else
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <br>
                    <h1 style="font-size: 3rem">Módulos</h1>
                </div>
            </div>
            <div style="display: none">{{$i = 0}}</div>
            <div class="row">
                @foreach($items as $item)
                    @if($i <= 0)
                        <div class="col-sm-6" style="margin-top: 5%">
                            <a href="item/present/{{ $item->id }}">
                                <img src="{{ $item->path() }}" alt="" width="90%">
                            </a>
                            <br>
                            <h2 style="margin-top: 2%">{{$item->name}}
                                @if ($item->current_user_items[0]->pivot->progress < 100)
                                    <span>{{ $item->current_user_items[0]->pivot->progress }}%</span>
                                    <div class="progress-label">
                                        <span>No terminado</span>
                                    </div>
                                @else
                                    <div class="progress-label">
                                        <span>Terminado</span>
                                    </div>
                                @endif

                            </h2>
                        </div>
                    @endif
                        <div style="display: none">{{$i = $i + 1}}</div>
                @endforeach
            </div>

        </div>

    @endif


    <script>
        $(document).ready(function () {
            $('#myTable').DataTable();
        });
    </script>
@endsection

@push('css')
    <link rel="stylesheet" href="{{ asset('argon') }}/vendor/datatables.net-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="{{ asset('argon') }}/vendor/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css">
    <link rel="stylesheet" href="{{ asset('argon') }}/vendor/datatables.net-select-bs4/css/select.bootstrap4.min.css">
@endpush

@push('js')
    <script src="{{ asset('argon') }}/vendor/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="{{ asset('argon') }}/vendor/datatables.net-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="{{ asset('argon') }}/vendor/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="{{ asset('argon') }}/vendor/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js"></script>
    <script src="{{ asset('argon') }}/vendor/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="{{ asset('argon') }}/vendor/datatables.net-buttons/js/buttons.flash.min.js"></script>
    <script src="{{ asset('argon') }}/vendor/datatables.net-buttons/js/buttons.print.min.js"></script>
    <script src="{{ asset('argon') }}/vendor/datatables.net-select/js/dataTables.select.min.js"></script>
@endpush